"""Inicialización de la base de datos

Revision ID: 7372b7158d7b
Revises: 
Create Date: 2024-12-14 19:33:21.907248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7372b7158d7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios_roles')
    with op.batch_alter_table('permisos', schema=None) as batch_op:
        batch_op.drop_index('nombre')

    op.drop_table('permisos')
    op.drop_table('edificios')
    op.drop_table('data_presurizacion')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index('correo')

    op.drop_table('usuarios')
    op.drop_table('data_co2')
    op.drop_table('pisos')
    op.drop_table('comandos')
    op.drop_table('roles_permisos')
    op.drop_table('usuarios_permisos')
    op.drop_table('señales')
    op.drop_table('mantenimiento')
    op.drop_table('sistemas')
    with op.batch_alter_table('data_usuarios', schema=None) as batch_op:
        batch_op.drop_index('dni')
        batch_op.drop_index('email')

    op.drop_table('data_usuarios')
    op.drop_table('estados')
    op.drop_table('equipos')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index('nombre')

    op.drop_table('roles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id_rol', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('descripcion', mysql.TEXT(), nullable=True),
    sa.Column('estatus', mysql.ENUM('Activo', 'Inactivo'), server_default=sa.text("'Activo'"), nullable=True),
    sa.PrimaryKeyConstraint('id_rol'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index('nombre', ['nombre'], unique=True)

    op.create_table('equipos',
    sa.Column('id_equipo', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_sistema', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('marca', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('modelo', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('descripcion', mysql.TEXT(), nullable=True),
    sa.Column('estatus', mysql.ENUM('Operativo', 'En Mantenimiento', 'Falla', 'Inactivo'), server_default=sa.text("'Operativo'"), nullable=True),
    sa.Column('fecha_instalacion', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_sistema'], ['sistemas.id_sistema'], name='equipos_ibfk_1'),
    sa.PrimaryKeyConstraint('id_equipo'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('estados',
    sa.Column('id_estado', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_sistema', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estado', mysql.ENUM('Parada', 'Marcha', 'Error'), nullable=False),
    sa.Column('fecha', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_sistema'], ['sistemas.id_sistema'], name='estados_ibfk_1'),
    sa.PrimaryKeyConstraint('id_estado'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('data_usuarios',
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('primer_nombre', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('segundo_nombre', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('primer_apellido', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('segundo_apellido', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('dni', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('edad', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sexo', mysql.ENUM('Masculino', 'Femenino', 'Otro'), nullable=True),
    sa.Column('especialidad', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('direccion', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('celular', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('fecha_registro', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='data_usuarios_ibfk_1'),
    sa.PrimaryKeyConstraint('id_usuario'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('data_usuarios', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)
        batch_op.create_index('dni', ['dni'], unique=True)

    op.create_table('sistemas',
    sa.Column('id_sistema', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('tipo', mysql.ENUM('Presurización', 'CO2', 'Bomba Presión', 'Otro'), nullable=False),
    sa.Column('id_piso', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estatus', mysql.ENUM('Activo', 'Inactivo'), server_default=sa.text("'Activo'"), nullable=True),
    sa.Column('fecha_instalacion', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_piso'], ['pisos.id_piso'], name='sistemas_ibfk_1'),
    sa.PrimaryKeyConstraint('id_sistema'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('mantenimiento',
    sa.Column('id_mantenimiento', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_sistema', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('observaciones', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['id_sistema'], ['sistemas.id_sistema'], name='mantenimiento_ibfk_1'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='mantenimiento_ibfk_2'),
    sa.PrimaryKeyConstraint('id_mantenimiento'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('señales',
    sa.Column('id_señal', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_sistema', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo_señal', mysql.ENUM('BMS', 'Humo', 'Incendio', 'Otro'), nullable=False),
    sa.Column('estatus', mysql.ENUM('Activo', 'Inactivo'), nullable=False),
    sa.Column('fecha', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_sistema'], ['sistemas.id_sistema'], name='señales_ibfk_1'),
    sa.PrimaryKeyConstraint('id_señal'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('usuarios_permisos',
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_permiso', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activo', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_permiso'], ['permisos.id_permiso'], name='usuarios_permisos_ibfk_2'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='usuarios_permisos_ibfk_1'),
    sa.PrimaryKeyConstraint('id_usuario', 'id_permiso'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('roles_permisos',
    sa.Column('id_rol', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_permiso', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_permiso'], ['permisos.id_permiso'], name='roles_permisos_ibfk_2'),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], name='roles_permisos_ibfk_1'),
    sa.PrimaryKeyConstraint('id_rol', 'id_permiso'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('comandos',
    sa.Column('id_comando', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_sistema', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo_comando', mysql.ENUM('Prender', 'Apagar', 'Cambiar Modo', 'Otro'), nullable=False),
    sa.Column('detalles', mysql.JSON(), nullable=True),
    sa.Column('fecha', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_sistema'], ['sistemas.id_sistema'], name='comandos_ibfk_1'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='comandos_ibfk_2'),
    sa.PrimaryKeyConstraint('id_comando'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('pisos',
    sa.Column('id_piso', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('id_edificio', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ubicacion', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_edificio'], ['edificios.id_edificio'], name='pisos_ibfk_1'),
    sa.PrimaryKeyConstraint('id_piso'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('data_co2',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_sistema', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('concentracion_co2', mysql.FLOAT(), nullable=True),
    sa.Column('presion', mysql.FLOAT(), nullable=True),
    sa.Column('temperatura', mysql.FLOAT(), nullable=True),
    sa.Column('flujo_aire', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['id_sistema'], ['sistemas.id_sistema'], name='data_co2_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('correo', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('contraseña', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('estatus', mysql.ENUM('Activo', 'Inactivo'), server_default=sa.text("'Activo'"), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index('correo', ['correo'], unique=True)

    op.create_table('data_presurizacion',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_sistema', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('tensionMotor', mysql.FLOAT(), nullable=True),
    sa.Column('tensionDC', mysql.FLOAT(), nullable=True),
    sa.Column('corriente', mysql.FLOAT(), nullable=True),
    sa.Column('potencia', mysql.FLOAT(), nullable=True),
    sa.Column('frecuencia', mysql.FLOAT(), nullable=True),
    sa.Column('temperatura', mysql.FLOAT(), nullable=True),
    sa.Column('IA', mysql.FLOAT(), nullable=True),
    sa.Column('AV', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['id_sistema'], ['sistemas.id_sistema'], name='data_presurizacion_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('edificios',
    sa.Column('id_edificio', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('direccion', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('ubicacion', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('estatus', mysql.ENUM('Activo', 'Inactivo'), server_default=sa.text("'Activo'"), nullable=True),
    sa.Column('fecha_creacion', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id_edificio'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('permisos',
    sa.Column('id_permiso', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('descripcion', mysql.TEXT(), nullable=True),
    sa.Column('estatus', mysql.ENUM('Activo', 'Inactivo'), server_default=sa.text("'Activo'"), nullable=True),
    sa.PrimaryKeyConstraint('id_permiso'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('permisos', schema=None) as batch_op:
        batch_op.create_index('nombre', ['nombre'], unique=True)

    op.create_table('usuarios_roles',
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_rol', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], name='usuarios_roles_ibfk_2'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='usuarios_roles_ibfk_1'),
    sa.PrimaryKeyConstraint('id_usuario', 'id_rol'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
